CREATE USER 'foyer' IDENTIFIED BY 'wawa';
CREATE DATABASE foyer;
GRANT ALL PRIVILEGES ON foyer.* TO 'foyer';
FLUSH PRIVILEGES;

USE foyer;

CREATE TABLE IF NOT EXISTS messages (
	id INT PRIMARY KEY AUTO_INCREMENT,
	message TEXT NOT NULL
);
