CREATE USER 'foyer' IDENTIFIED BY 'wawa';
CREATE DATABASE foyer;
GRANT ALL PRIVILEGES ON foyer.* TO 'foyer';
FLUSH PRIVILEGES;

USE foyer;

CREATE TABLE IF NOT EXISTS users (
	id INT PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(8) NOT NULL,
	password_hash VARCHAR(100) NOT NULL,
	grade INT NOT NULL
);

CREATE TABLE IF NOT EXISTS shifts (
	id INT PRIMARY KEY AUTO_INCREMENT,
	shift_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS shift_user (
	id INT PRIMARY KEY AUTO_INCREMENT,
	user_id INT NOT NULL REFERENCES users(id),
	shift_id INT NOT NULL REFERENCES shifts(id)
);
